### ISSUE TITLE
Shorten Github Issues concourse workflow check every period to 15m

### ISSUE THREAD

**Issue by feoh** [mitodl/ol-infrastructure#2642]
### Expected Behavior
I would expect that the Concourse pipeline would start deploying within a reasonable time frame after I close the controlling Github issue. Currently this is set to 1h which is far too long to wait in a release day context.

### Current Behavior
You have to wait an hour which will not fly during a release or in a crisis.

**Comment by feoh** [comment]
This change is in. From the docker-packer-pulumi-edx-global pipeline as viewed with get-pipeline:
```
- check_every: 15m0s
  expose_build_created_by: true
  icon: github
  name: github-issues-applications.edxapp.mitx.ci-post
  source:
    access_token: ((github.issues_resource_access_token))
    auth_method: token
    gh_host: https://github.mit.edu/api/v3
    issue_prefix: '[bot] Pulumi ol-infrastructure-edxapp-application.mitx applications.edxapp.mitx.CI
      deployed.'
    issue_state: open
    issue_title_template: '[bot] Pulumi ol-infrastructure-edxapp-application.mitx
      applications.edxapp.mitx.CI deployed.'
    repository: ol-platform-eng/concourse-workflow
  type: github-issues
- check_every: 15m0s
  expose_build_created_by: true
  icon: github
  name: github-issues-applications.edxapp.mitx.ci-trigger

```
