### ISSUE TITLE
OCW caching needs to be adjusted

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ol-infrastructure#555]
When a site pipeline is triggered in Concourse, one of the steps currently busts the cache using:

```
      - task: clear-cdn-cache
        timeout: 5m
        attempts: 3
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: curlimages/curl}
          run:
            path: curl
            args:
              - -f
              - -X
              - POST
              - -H
              - 'Fastly-Key: ((fastly.api_token))'((purge_header))
              - https://api.fastly.com/service/((fastly.service_id))/((purge-url))
```

This successfully busts the cache at the Fastly URL, but the `ocwnext-rc/ocwnext` CNAME's seem to be putting their own cache in front of everything.  For example, if you visit https://ocw-live-qa.global.ssl.fastly.net/search/ and look in the console in your web browser you will see an error related to CORS:

```
ocw-live-qa.global.ssl.fastly.net/:1 Access to fetch at 'https://discussions-rc.odl.mit.edu/api/v0/search/' from origin 'https://ocw-live-qa.global.ssl.fastly.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

This indicates that `ocw-www` was successfully built when I added `SEARCH_API_URL` and rebuilt it and the cache was successfully busted at ocw-live-qa.global.ssl.fastly.net.  However if you view https://ocwnext-rc.odl.mit.edu/search/ and look at the console, you see `VM179:1 GET https://ocwnext-rc.odl.mit.edu/search/undefined/ 404`, indicating that the old JS is still being served before I added `SEARCH_API_URL` and redeployed the site.
