### ISSUE TITLE
Move Heroku settings management to Concourse

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#620]
Right now we are using SaltStack as the mechanism for populating the configuration of our applications in Heroku. This has proven problematic due to the lack of visibility when there are failures to execute the schedule. To resolve this situation we will provision static IAM credentials for use with AWS resources, as well as migrating our population of Heroku settings into Concourse pipelines that are easier for developers to trigger independently and make failures more visible.
```[tasklist]
### Tasks
- [x] Set up Heroku configurator Python project (repo, poetry, dependencies)
- [x] Identify all secrets currently living in Heroku app configs
- [x] Write Heroku configurator as a Concourse resource that reads configuration vars and values from YAML
- [x] Write Pydantic model that can import the Concourse Vault resource secrets.json and export the herokuconfigurator YAML
- [ ] Write Vault Pydantic model so our pipeline definition can be in Python
- [ ] Figure out the source of truth for configurables created by Pulumi e.g. DATABASE_URL - Salt uses Boto
- [ ] How does the Micromasters Pydantic model integrate with the pipeline?
- [ ] Figure out how to get Pydantic models to populate per environment
- [ ] Write Concourse pipeline definitions to pull Heroku configs from Vault and possibly Consul and write the YAML file the Heroku Configurator Concourse resource defined in the prior step will use
- [ ] Test and remove current Heroku configuration from Saltstack
```

**Comment by blarghmatey** [comment]
This is blocked waiting for completion of #1500

**Comment by blarghmatey** [comment]
The work on #1500 is now complete enough to unblock this work.

**Comment by feoh** [comment]
Potentially use [this Python wrapper](https://github.com/martyzz1/heroku3.py) to call the Heroku API.

**Comment by feoh** [comment]
[This](https://github.com/mitodl/salt-ops/blob/main/pillar/heroku/micromasters.sls) is an example of the current configuration Salt uses, in this case for the micromasters app.

My tool should suck equivalent configuration out of ol_infrastructure and make the relevant changes in Heroku's config.

**Comment by blarghmatey** [comment]
For reference here is a sample pipeline for interacting with Vault and loading the values as pipeline vars
```yaml
resource_types:
- name: vault
  type: docker-image
  source:
    repository: mitodl/concourse-vault-resource
    tag: latest

resources:
- name: vault-postgres-mitxonline
  type: vault
  source:
    address: https://vault-qa.odl.mit.edu:443
    auth_engine: aws
    aws_vault_role: concourse-vault-resource
    secret:
      mount: postgres-mitxonline
      path: readonly
      engine: database

- name: vault-secret
  type: vault
  source:
    address: https://vault-qa.odl.mit.edu:443
    auth_engine: aws
    aws_vault_role: concourse-vault-resource
    secret:
      mount: secret-airbyte
      path: pomerium
      engine: kv2

- name: vault-out
  type: vault
  source:
    address: https://vault-qa.odl.mit.edu:443
    auth_engine: aws
    aws_vault_role: concourse-vault-resource

jobs:
- name: do-something
  plan:
  - get: vault-postgres-mitxonline
    # params:
    #   postgres-mitxonline:
    #     paths:
    #       - readonly
    #     engine: database
  - get: vault-secret
    # params:
    #   secret-airbyte:
    #     paths:
    #       - pomerium
    #     engine: kv2
  - load_var: postgres
    file: vault-postgres-mitxonline/vault.json
  - load_var: secret
    file: vault-secret/vault.json
  - put: vault-out
    no_get: true
    params:
      secret:
        engine: kv1
        secrets:
          test_db:
            db_user: ((.:postgres.postgres-mitxonline-readonly.username))
            db_pass: ((.:postgres.postgres-mitxonline-readonly.password))
          test_pomerium:
            pomerium: ((.:secret.secret-airbyte-pomerium))
```
